FROM node:lts-alpine as build-stage
# Create app directory
WORKDIR /app
COPY package*.json ./
# install app dependencies
RUN npm install
# Bundle app source
COPY . .
# build app for production with minification
RUN npm run build

# Static files from hereon

# demo stage
FROM nginx:stable-alpine as demo-stage
## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]